<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>a974e73e-009f-4b2a-9ea6-00ee8f98851f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.19" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.17" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.17">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\KASHOP.BLL\KASHOP.BLL.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="wwwroot\images\MainImage" />
  </ItemGroup>

</Project>
